### ISSUE TITLE
run as service

### ISSUE THREAD

**Issue by irghost** [isislovecruft/obfsproxy#2]
how can i run obfsproxy which is running on my centos6.6 server   after restart like service

**Comment by isislovecruft** [comment]
Try putting `@reboot COMMAND` into the crontab of whichever user should be running obfsproxy, where `COMMAND` is whatever command you use to start obfsproxy.

Also, this is *not* [the canonical repo for obfsproxy](https://gitweb.torproject.org/pluggable-transports/obfsproxy.git), it is my personal fork. Also, a ticket usually not the place to be asking for help with Tor things. In this case, you should try [the tor-relays mailing list](mailto:tor-relays@lists.torproject.org) if you need further assistance.
